name: Build & deploy
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache modules
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubActions
          aws-region: us-east-2
      - name: Use Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Deploy
        run: aws s3 sync ./build s3://${{ secrets.S3_BUCKET_NAME }}
      - name: Invalidate Cloudfront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_DISTRUBUTION_ID }} --paths "/*"
